apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ${{ values.image_repository }}

namespace: apps

commonLabels:
  app: ${{ values.service_name }}
  environment: dev
