apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.service_name }}-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: service=${{ values.image_repository }}
    argocd-image-updater.argoproj.io/service.platforms: linux/amd64
    argocd-image-updater.argoproj.io/service.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    app: ${{ values.service_name }}
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/sajjadkhan-academy/argocd-centralized-repo-idp.git
    targetRevision: main
    path: apps/${{ values.service_name }}/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
